import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "/globals.css";
import TransitionProvider from "@/components/TransitionProvider";
import React from "react";
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ghachim Portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string};
}>
) {
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={inter.className}>
      <NextIntlClientProvider messages={messages}>
        <TransitionProvider>
          {children}
        </TransitionProvider>
      </NextIntlClientProvider>  
      </body>
    </html>
  );
}
